flowchart LR
    classDef us fill:#e3f2fd,stroke:#1565c0,color:#0d47a1
    classDef setting fill:#fff3e0,stroke:#ef6c00,color:#e65100
    classDef screen fill:#e8f5e9,stroke:#2e7d32,color:#1b5e20

    subgraph RULES["Общие правила"]
        R1["Планшет / диалог / журнал"]:::us
        R1 --> R1A["Н01, Н02"]:::setting
        R1 --> R1B["Экран входа<br/>Рабочий экран<br/>Журнал"]:::screen
    end

    subgraph E1["Эпик 1. Смена наладчика"]
        US11["US-1.1<br/>Завершение чужой смены"]:::us
        US11 --> US11A["Н01"]:::setting
        US11 --> US11B["Экран входа<br/>диалог сеанса"]:::screen

        US12["US-1.2<br/>Авторизация"]:::us
        US12 --> US12A["Н01, Н02"]:::setting
        US12 --> US12B["Экран входа"]:::screen

        US13["US-1.3<br/>Выбор задания"]:::us
        US13 --> US13A["Н07"]:::setting
        US13 --> US13B["Рабочий экран<br/>выбор детали"]:::screen

        US14["US-1.4<br/>Нет задания"]:::us
        US14 --> US14A["Н01, Н07"]:::setting
        US14 --> US14B["Рабочий экран<br/>сообщение менеджеру"]:::screen
    end

    subgraph E2["Эпик 2. Приём рабочего места"]
        US21["US-2.1<br/>Схема сборки"]:::us
        US21 --> US21A["Н01, Н06"]:::setting
        US21 --> US21B["Схема сборки<br/>карточка позиции"]:::screen

        US22["US-2.2<br/>Приём годного инструмента"]:::us
        US22 --> US22A["Н08, Н09, Н10, Н44"]:::setting
        US22 --> US22B["Приём смены<br/>Остатки"]:::screen

        US23["US-2.3<br/>Начальное показание"]:::us
        US23 --> US23A["Н03, Н04, Н05"]:::setting
        US23 --> US23B["Ввод показания"]:::screen
    end

    subgraph E3["Эпик 3. Контроль ресурса и замена"]
        US31["US-3.1<br/>Прогноз наработки"]:::us
        US31 --> US31A["Н04, Н05, Н06, Н13"]:::setting
        US31 --> US31B["Рабочий экран"]:::screen

        US32["US-3.2<br/>Реакция на предупреждение"]:::us
        US32 --> US32A["Н12, Н37, Н42"]:::setting
        US32 --> US32B["Рабочий экран<br/>мигание / КОНТРОЛИРУЮ"]:::screen

        US33["US-3.3<br/>Замена сверла"]:::us
        US33 --> US33A["Н10, Н38, Н44"]:::setting
        US33 --> US33B["Замена инструмента"]:::screen

        US34["US-3.4<br/>Ранняя замена"]:::us
        US34 --> US34A["Н42"]:::setting
        US34 --> US34B["Замена инструмента<br/>сообщение о проблеме"]:::screen

        US35["US-3.5<br/>Замена пластин"]:::us
        US35 --> US35A["Н38, Н39, Н40, Н41"]:::setting
        US35 --> US35B["Замена → Пластины"]:::screen

        US36["US-3.6<br/>Обнуление прогноза"]:::us
        US36 --> US36A["Н42, Н43"]:::setting
        US36 --> US36B["Инструмент<br/>Обнулить прогноз"]:::screen
    end

    subgraph E4["Эпик 4. Заказ и получение"]
        US41["US-4.1<br/>Заказ инструмента"]:::us
        US41 --> US41A["Н14, Н15, Н16, Н17"]:::setting
        US41 --> US41B["Заказ<br/>Рекомендация"]:::screen

        US42["US-4.2<br/>Корректировка заявки"]:::us
        US42 --> US42A["Н17, Н18, Н19"]:::setting
        US42 --> US42B["Заказ<br/>Изменение количества"]:::screen

        US43["US-4.3<br/>Получение инструмента"]:::us
        US43 --> US43A["Н20, Н08"]:::setting
        US43 --> US43B["Получение<br/>сверка и корректировка"]:::screen

        US44["US-4.4<br/>Изменение заявки в доставке"]:::us
        US44 --> US44A["Н19"]:::setting
        US44 --> US44B["Получение<br/>доставка + остаток"]:::screen

        US45["US-4.5<br/>Аварийное получение"]:::us
        US45 --> US45A["Н20, В05"]:::setting
        US45 --> US45B["Резерв<br/>запрос доступа"]:::screen
    end

    subgraph E5["Эпик 5. Проблемы и SOS"]
        US51["US-5.1<br/>Сообщение о проблеме"]:::us
        US51 --> US51A["Н21, Н22"]:::setting
        US51 --> US51B["Сообщить о проблеме"]:::screen

        US52["US-5.2<br/>SOS"]:::us
        US52 --> US52A["Н21, Н22"]:::setting
        US52 --> US52B["SOS"]:::screen

        US53["US-5.3<br/>Принятие и возобновление"]:::us
        US53 --> US53A["Н23, Н27"]:::setting
        US53 --> US53B["SOS<br/>возобновление работы"]:::screen

        US54["US-5.4<br/>Передача смены при SOS"]:::us
        US54 --> US54A["Н05"]:::setting
        US54 --> US54B["Завершение смены<br/>открытый SOS"]:::screen

        US55["US-5.5<br/>Отмена ложной тревоги"]:::us
        US55 --> US55A["Н27"]:::setting
        US55 --> US55B["SOS<br/>отмена"]:::screen

        US56["US-5.6<br/>SOS в выходной и эскалация"]:::us
        US56 --> US56A["Н24, Н25, Н26"]:::setting
        US56 --> US56B["SOS<br/>цепочка ответственных"]:::screen

        US57["US-5.7<br/>SOS без связи"]:::us
        US57 --> US57A["Н25, В11"]:::setting
        US57 --> US57B["SOS<br/>локальное сохранение"]:::screen
    end

    subgraph E6["Эпик 6. Смена задания и завершение смены"]
        US61["US-6.1<br/>Смена задания"]:::us
        US61 --> US61A["Н03, Н07"]:::setting
        US61 --> US61B["Смена задания"]:::screen

        US62["US-6.2<br/>Один или несколько счётчиков"]:::us
        US62 --> US62A["Н03"]:::setting
        US62 --> US62B["Рабочий экран<br/>поля счётчиков"]:::screen

        US63["US-6.3<br/>Завершение смены"]:::us
        US63 --> US63A["Н03, Н11"]:::setting
        US63 --> US63B["Завершение смены"]:::screen

        US64["US-6.4<br/>Исправление ошибки"]:::us
        US64 --> US64A["Н28, Н29"]:::setting
        US64 --> US64B["Журнал<br/>исправление записи"]:::screen
    end

    subgraph E7["Эпик 7. Предложение нормы"]
        US71["US-7.1<br/>Предложение нормы"]:::us
        US71 --> US71A["Н31, Н33"]:::setting
        US71 --> US71B["Норма<br/>корректировка"]:::screen

        US72["US-7.2<br/>Временная норма"]:::us
        US72 --> US72A["Н32, Н33, Н34"]:::setting
        US72 --> US72B["Норма<br/>ожидает подтверждения"]:::screen

        US73["US-7.3<br/>Получение решения"]:::us
        US73 --> US73A["Н35, Н36"]:::setting
        US73 --> US73B["Норма<br/>решение менеджера"]:::screen
    end

    subgraph E8["Эпик 8. Работа без связи"]
        US81["US-8.1<br/>Замена без связи"]:::us
        US81 --> US81A["В11"]:::setting
        US81 --> US81B["Замена инструмента<br/>локальное сохранение"]:::screen

        US82["US-8.2<br/>Неотправленная заявка"]:::us
        US82 --> US82A["Н25, В11"]:::setting
        US82 --> US82B["Заказ<br/>не отправлено"]:::screen

        US83["US-8.3<br/>Приёмка по бумаге"]:::us
        US83 --> US83A["Н20, В11"]:::setting
        US83 --> US83B["Бумажный бланк<br/>перенос"]:::screen

        US84["US-8.4<br/>Восстановление после перезагрузки"]:::us
        US84 --> US84A["В11"]:::setting
        US84 --> US84B["Рабочий экран<br/>восстановление очереди"]:::screen

        US85["US-8.5<br/>Аварийный ручной режим"]:::us
        US85 --> US85A["Н20, В11"]:::setting
        US85 --> US85B["Бумажный бланк смены"]:::screen
    end